module.exports = {
  PARTY_STATUS: {
    PENDING: 'PENDING',
    DEPLOYED: 'DEPLOYED',
  },
  PARTICIPANT_STATUS: {
    UNKNOWN: 'UNKNOWN',
    REGISTERED: 'REGISTERED',
    SHOWED_UP: 'SHOWED_UP',
    WITHDRAWN_PAYOUT: 'WITHDRAWN_PAYOUT',
  },
}
