export const SIGN_IN = 'sign_in'
export const EDIT_PROFILE = 'edit_profile'
export const CONFIRM_TRANSACTION = 'confirm_transaction'
export const SIGN_IN_CHOICE = 'sign_in_choice'
export const UNIVERSAL_LOGIN = 'universal_login'
